github:
  branch: master
  repository: https://github.com/api-ninja/sw-concourse-training.git
  username: api-ninja
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: nginx
    release: nginx
  name: nginx
  networks:
  - name: default
  stemcell: default
  vm_type: small
meta:
  name: api-ninja-nginx-demo
  pipeline: api-ninja-nginx-demo
  target: training
  url: https://pipes.starkandwayne.com
name: ninja-release
release:
  name: nginx-release
releases:
- name: nginx
  version: latest
stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3586.46
update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 10
  update_watch_time: 1000-30000

